### ISSUE TITLE
Question: what is the status line plugin

### ISSUE THREAD

**Issue by ryoppippi** [levouh/tint.nvim#32]
I'm wondering what is the status line on the demo screenshot. It looks so cool

**Comment by levouh** [comment]
It is my own personal implementation that I have not "vendored" anywhere at the moment, nor are my configuration files public because they currently contain too much work-related stuff.

Let me see if I can find a way to share it with you otherwise (a simple copy/paste would not quite suffice as it is spread across multiple files in my own config).

**Comment by ryoppippi** [comment]
@levouh Thank you!

**Comment by levouh** [comment]
Going to close this as I recently switched out my own internal statusline implementation, and it would take more work than I'm willing to put in to export it. Sorry.
